import Navigation from "@/components/fragments/Navigation"
import Sidebar from "@/components/fragments/Sidebar"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative h-screen`}
      >
        <Navigation/>
        <Sidebar/>
        <main className="absolute top-0 left-0 pl-20 py-[4rem] w-full h-full bg-slate-100 text-slate-800">{children}</main>
      </body>
    </html>
  );
}